---
title: "EDA Data Cleanup"
output: html_notebook
---

```{r}
library(readr)
library(tidyverse)
library(gridExtra)
```

```{r}
CBB = read_csv("cbb.csv")
names(CBB)
CBB <- CBB %>% 
  rename(School=TEAM) %>% 
  rename(Conference=CONF) %>% 
  rename(GamesPlayed = G) %>% 
  rename(GamesWon = W) %>% 
  rename(AdjustedOffensiveEfficiency=ADJOE) %>% 
  rename(AdjustedDefensiveEfficiency=ADJDE) %>% 
  rename(PowerRating = BARTHAG) %>% 
  rename(EffectiveFieldGoalPercentageShot=EFG_O) %>% 
  rename(EffectiveFieldGoalPercentageAllowed=EFG_D) %>% 
  rename(TurnoverRate=TOR) %>% 
  rename(StealRate=TORD) %>% 
  rename(OffensiveReboundRate=ORB) %>% 
  rename(OffensiveReboundRateAllowed=DRB) %>% 
  rename(FreeThrowRate=FTR) %>%
  rename(FreeThrowRateAllowed = FTRD) %>% 
  rename(TwoPointShootingPercentage = "2P_O") %>% 
  rename(TwoPointShootingPercentageAllowed='2P_D') %>% 
  rename(ThreePointShootingPercentage='3P_O') %>% 
  rename(ThreePointShootingPercentageAllowed='3P_D') %>% 
  rename(AdjustedTempo=ADJ_T) %>% 
  rename(WinsAboveBubble=WAB) %>% 
  rename(Postseason=POSTSEASON) %>% 
  rename(Seed=SEED) %>% 
  rename(Season=YEAR)

```

```{r}
q1 <- filter(CBB, !is.na(Postseason)) %>% 
  mutate(WinningPercentage = GamesWon / GamesPlayed)

q1$Postseason[q1$Postseason == "Champions"] <- 1
q1$Postseason[q1$Postseason == "2ND"] <- 2
q1$Postseason[q1$Postseason == "F4"] <- 3
q1$Postseason[q1$Postseason == "E8"] <- 4
q1$Postseason[q1$Postseason == "S16"] <- 5
q1$Postseason[q1$Postseason == "R32"] <- 6
q1$Postseason[q1$Postseason == "R64"] <- 7
q1$Postseason[q1$Postseason == "R68"] <- 8
```

```{r}
q1b = q1[,c(3, 4, 25, 5:24)]
none = lm(Postseason~1, data=q1b)
full = lm(Postseason~., data=q1b)
stepAIC(none, scope=list(upper=full), direction="both", trace=FALSE)
```

```{r}
plot(Postseason ~ GamesPlayed + GamesWon + WinningPercentage + PowerRating + AdjustedTempo + OffensiveReboundRateAllowed + FreeThrowRate, data = q1b)

q1_model = lm(Postseason ~ GamesPlayed + GamesWon + WinningPercentage + PowerRating + AdjustedTempo + OffensiveReboundRateAllowed + FreeThrowRate, data = q1b)

abline(q1_model)
```

```{r}
plot(q1_model)
```

```{r}
q2 <- q1[c(2,22)] 
q2$Conference <- as.factor(q2$Conference)
q2$Postseason <- as.numeric(q2$Postseason)

boxplot(Postseason~factor(Conference), data=q2)

means = tapply(q2$Postseason, q2$Conference, mean)
points(means, col="red", pch=18)
```

```{r}
q2_anova = aov(Postseason~factor(Conference), data=q2)
q2_anova
plot(q2_anova)
# q2_anova plot satisfies criteria
summary(q2_anova)
# P-value is low -> reject the null (that all means are the same), which means that the groups are different
```

```{r, eval=F}
# See which groups are the most different
pairwise.t.test(q2$Postseason, q2$Conference, p.adj="none")
```

```{r}
q2_plot = TukeyHSD(q2_anova)
plot(q2_plot)
```

```{r}

q3<- ggplot(data=CBB) +
  geom_point(aes(x=TurnoverRate,y=GamesWon)) +
  geom_smooth(aes(x=TurnoverRate,y=GamesWon)) + 
  xlab("Turnover Rate")+ylab("Games Won")

q3
```

```{r}

q4<-ggplot(data=filter(CBB,Conference=="ACC")) +
  geom_point(aes(x=PowerRating,y= GamesWon/GamesPlayed))+
  geom_smooth(aes(x=PowerRating,y= GamesWon/GamesPlayed))+
  ggtitle("Power Rating Efficiency in the ACC")+
  xlab("Power Rating") +ylab("Average Win")

q4
```



```{r}
q5 = ggplot(data=CBB) +
  geom_point(aes(x=FreeThrowRate,y=GamesWon)) +
  xlab("Free Throw Percentage")+ylab("Games Won") + geom_smooth(aes(x=FreeThrowRate,y=GamesWon))
q5
```


```{r}
q6 = ggplot(data=CBB) +
  geom_point(aes(x=AdjustedOffensiveEfficiency,y= GamesWon / GamesPlayed)) +
  xlab("Offensive Efficiency")+ylab("Winning Percentage") + geom_smooth(aes(x=AdjustedOffensiveEfficiency,y= GamesWon / GamesPlayed))
q6
```




```{r}
#Plots for q7
q7plot.1 = ggplot(data=CBB, aes(x=AdjustedOffensiveEfficiency, y=PowerRating)) +
  geom_point()

q8plot.2 = ggplot(data=CBB, aes(x=AdjustedDefensiveEfficiency, y=PowerRating)) +
  geom_point()

grid.arrange(q7plot.1, q8plot.2, ncol=2)
```

```{r}
#Plot for q8
q8plot.1 = CBB %>%
  group_by(Conference) %>%
  summarise(Count = n(), GamesWonAvg = mean(GamesWon)) %>%
  arrange(desc(Count)) %>%
  ggplot(aes(x=Conference, y=GamesWonAvg)) +
    geom_bar(stat='identity')

q8plot.1
```



```{r}
#Plot for q9
q9 <- ggplot(data=CBB, aes(x=TwoPointShootingPercentageAllowed,y=ThreePointShootingPercentageAllowed)) + 
  geom_point()+
  stat_regline_equation(label.y = 40, aes(label = ..rr.label..))

q9
```


```{r}
#Plot for q10
q10.1 <- ggplot(data=CBB, aes(x=ThreePointShootingPercentage,y=AdjustedOffensiveEfficiency)) + 
  geom_point() + 
  geom_smooth(method = "lm", se = FALSE) +
  stat_regline_equation(label.y = 120, aes(label = ..rr.label..))
           

q10.2 <- ggplot(data=CBB, aes(x=TwoPointShootingPercentage, y=AdjustedOffensiveEfficiency)) + 
  geom_point() + 
  geom_smooth(method = "lm", se = FALSE) +
  stat_regline_equation(label.y = 120, aes(label = ..rr.label..))
  

grid.arrange(q10.1, q10.2, ncol=1)
```

```{r}
q11<-ggplot(data=CBB) +
  geom_point(aes(x=ThreePointShootingPercentage,y= GamesWon))+
  geom_smooth(aes(x=ThreePointShootingPercentage,y= GamesWon))+
  ggtitle("Correlation Between 3P Shooting Percentage and Games Won")+
  xlab("3P Shooting %") +ylab("Games Won")
q11
```

```{r}
q12<-ggplot(data=CBB) +
  geom_point(aes(x=TwoPointShootingPercentageAllowed,y= FreeThrowRateAllowed))+
  geom_smooth(aes(x=TwoPointShootingPercentageAllowed,y= FreeThrowRateAllowed))+
  ggtitle("Correlation Between Allowed 2pt Shooting % and Free Throw Rate Allowed")+
  xlab("2pt Shot Shooting Percentage Allowed") +ylab("Free Throw Rate Alowed")
q12

```



# >>>>>>> 32a90b4d8188f3c752b6b224b5b5e8b9a8e128d0
